# Generated by Django 2.2.2 on 2019-07-04 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenada',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 14, 16, 17, 25478, tzinfo=utc), verbose_name='instante'),
        ),
    ]
