# Generated by Django 2.2.2 on 2019-07-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='instante')),
                ('pitch', models.FloatField()),
                ('yaw', models.FloatField()),
                ('roll', models.FloatField()),
            ],
        ),
    ]
