# Generated by Django 2.2.1 on 2019-07-04 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_auto_20190704_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenada',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 17, 46, 55, 85807, tzinfo=utc), verbose_name='instante'),
        ),
    ]
